camltk416 -> camltk418. Does not segfault!!

diff --git a/external/ocamltk/Makefile b/external/ocamltk/Makefile
--- a/external/ocamltk/Makefile
+++ b/external/ocamltk/Makefile
@@ -19,6 +19,8 @@ Makefile.config:
 	@echo "You must configure first. Read INSTALL."
 	exit 1
 
+allopt: opt
+
 opt:	Makefile.config
 	cd support; $(MAKE) opt
 	cd lib; $(MAKE) -f Makefile.gen; $(MAKE) opt
@@ -29,11 +31,19 @@ opt:	Makefile.config
 	cd tk80; $(MAKE) opt
 
 lib: Widgets.src
-	compiler/tkcompiler
+	compiler/tkcompiler$(EXE) -outdir lib
 	cd lib; $(MAKE)
+
+top: lib/camltk.cma
+	ocamlmktop -verbose -cclib -Lsupport -I lib -custom camltk.cma \
+                -o camltktop
+        # to launch: ./camltktop -I lib -I support
+
+.PHONY: install
 
 install: 
 	test -d $(INSTALLDIR) || mkdir $(INSTALLDIR)
+	/bin/rm -rf $(INSTALLDIR)/*
 	cp Makefile.camltk $(INSTALLDIR)
 	cd lib; $(MAKE) install
 	cd support; $(MAKE) install
@@ -44,6 +54,9 @@ install:
 	cd tkanim; $(MAKE) install
 	cd tk80; $(MAKE) install
 	cd safe; $(MAKE) install
+
+uninstall:
+	- rm -rf $(INSTALLDIR)
 
 installopt: 
 	test -d $(INSTALLDIR) || mkdir $(INSTALLDIR)
@@ -60,7 +73,8 @@ clean :
 	cd $$d; $(MAKE) clean; cd ..; \
 	done
 
-distclean:  clean
+distclean: clean
+	cd tkanim; make distclean
 	-rm -f config.log config.status config.cache
 	-rm -f Makefile.config Makefile.camltk
 
@@ -70,23 +84,42 @@ FTPDIR=/net/pauillac/infosystems/ftp/cristal/caml-light/bazar-ocaml/ocamltk
 
 # thread-tk is too old code: do not distribute
 
-distribute:
+CAMLTKVERSION=418
+
+distribute: tarfile website rpm
+	$(MAKE) cleantar
+
+cleantar:
 	rm -rf release
+
+website:
 	rm -rf $(WEBSITEDIR)/*
+	cd release; \
+	cp -pr bazar-ocaml/camltk$(CAMLTKVERSION)/doc/* $(WEBSITEDIR); \
+	ln -s $(WEBSITEDIR)/eng.htm $(WEBSITEDIR)/index.html
+	- chgrp -R caml $(WEBSITEDIR)
+	- chmod -R g+w $(WEBSITEDIR)
+
+tarfile: cleantar
 	mkdir release
 	cd release; cvs co bazar-ocaml/camltk41; \
 	rm -rf bazar-ocaml/camltk41/thread-tk; \
 	find . -name '.cvsignore' -print | xargs rm; \
 	find . -name 'CVS' -print | xargs rm -rf; \
 	cp -p bazar-ocaml/camltk41/INSTALL bazar-ocaml/camltk41/doc/; \
-	cp -pr bazar-ocaml/camltk41/doc/* $(WEBSITEDIR); \
-	ln -s $(WEBSITEDIR)/eng.htm $(WEBSITEDIR)/index.html
-	- chgrp -R caml $(WEBSITEDIR)
-	- chmod -R g+w $(WEBSITEDIR)
-	cd release; mv bazar-ocaml/camltk41 camltk416; \
-	tar cvf ocamltk416.tar camltk416; \
-	gzip ocamltk416.tar; \
-	mv -f ocamltk416.tar.gz $(FTPDIR)
-	chgrp caml $(FTPDIR)/ocamltk416.tar.gz 	
-	rm -rf release
+	mv bazar-ocaml/camltk41 bazar-ocaml/camltk$(CAMLTKVERSION); \
+	cd bazar-ocaml; \
+	tar cvf ocamltk$(CAMLTKVERSION).tar camltk$(CAMLTKVERSION); \
+	gzip ocamltk$(CAMLTKVERSION).tar; \
+	mv -f ocamltk$(CAMLTKVERSION).tar.gz $(FTPDIR)
+	chgrp caml $(FTPDIR)/ocamltk$(CAMLTKVERSION).tar.gz
 
+rpm:
+	if test -d /usr/src/redhat; then rpmdir=/usr/src/redhat; \
+	else if test -d /usr/src/RPM; then rpmdir=/usr/src/RPM; fi; fi; \
+	if test "X$$rpmdir" = "X"; then \
+		echo "cannot create rpm"; exit 2; fi; \
+	echo YOU NEED TO SU ROOT; \
+	su root -c "cp $(FTPDIR)/ocamltk$(CAMLTKVERSION).tar.gz $$rpmdir/SOURCES/; rpm -ba --clean ./camltk.spec"; \
+	cp $$rpmdir/SRPMS/camltk-0.$(CAMLTKVERSION)-1.src.rpm \
+	   $$rpmdir/RPMS/*/camltk-0.$(CAMLTKVERSION)-1.*.rpm $(FTPDIR)
